services:
  web:
    #Servidor web que volem protegit
    image: php:8.2-apache
    volumes:
      - ./web:/var/www/html
    # No cal exposar el port 80, ja que el tràfic va a través de la xarxa interna de docker
    # És més, no HEM d'exposar el port, ja que el servidor web no ha  de ser accessible
    # des de l'exterior, tot ha de passar pel proxy invers - waf


  waf:
    #Basat en el ModSecurity Core Rule Set de la fundació OWASP
    #https://coreruleset.org/
    #https://github.com/coreruleset/modsecurity-crs-docker
    image: owasp/modsecurity-crs:apache
    environment:
      SERVERNAME: modsec2-apache
      #Refenciem el contenidor web pel seu nom, docker ja en farà la resolució
      #El contenidor web no necessita exposar el port 80
      #perquè el tràfic va a través de la xarxa interna de docker
      BACKEND: http://web
      PORT: "80"
      #MODSEC_RULE_ENGINE: DetectionOnly
      MODSEC_RULE_ENGINE: On
      BLOCKING_PARANOIA: 2
      TZ: "${TZ}"
      ERRORLOG: "/var/log/error.log"
      ACCESSLOG: "/var/log/access.log"
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG: "/var/log/modsec_audit.log"
      MODSEC_TMP_DIR: "/tmp"
      MODSEC_RESP_BODY_ACCESS: "On"
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      COMBINED_FILE_SIZES: "65535"
    ports:
      #En màquines windows és complicat exposar el port 80, 
      - "9000:80"
